spring:
  config:
    activate:
      on-profile: jpa
  datasource:
    url: jdbc:postgresql://localhost:5444/musicaTracks
    username: postgres
    password: pass
    hikari:
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:/postgres/musica-data.sql